part of '../main.dart';

// Categories, cities, conditions and related lookup data.

const List<String> pakistanCities = [
  'Abbottabad',
  'Adilpur',
  'Ahmadpur East',
  'Akora Khattak',
  'Aliabad (Hunza)',
  'Alipur',
  'Arifwala',
  'Astore',
  'Athmuqam',
  'Attock',
  'Awaran',
  'Badin',
  'Bagh',
  'Bahawalnagar',
  'Bahawalpur',
  'Balakot',
  'Bannu',
  'Barkhan',
  'Batkhela',
  'Battagram',
  'Bela',
  'Bhakkar',
  'Bhalwal',
  'Bhera',
  'Bhimber',
  'Bhiria',
  'Bostan',
  'Burewala',
  'Chak Azam',
  'Chak Jhumra',
  'Chakwal',
  'Chaman',
  'Charsadda',
  'Chichawatni',
  'Chilas',
  'Chiniot',
  'Chishtian',
  'Chitral',
  'Choa Saidan Shah',
  'Chuharkana',
  'Chunian',
  'Dadu',
  'Dadyal',
  'Daggar',
  'Daharki',
  'Dalbandin',
  'Daska',
  'Daud Khel',
  'Depalpur',
  'Dera Allah Yar',
  'Dera Bugti',
  'Dera Ghazi Khan',
  'Dera Ismail Khan',
  'Dera Murad Jamali',
  'Digri',
  'Dinga',
  'Dir',
  'Dokri',
  'Dunga Bunga',
  'Dunyapur',
  'Faisalabad',
  'Fort Abbas',
  'Fortabbas',
  'Forward Kahuta',
  'Gahkuch',
  'Gambat',
  'Garhi Khairo',
  'Ghotki',
  'Gilgit',
  'Gojra',
  'Gujar Khan',
  'Gujranwala',
  'Gujrat',
  'Gupis',
  'Gwadar',
  'Hadali',
  'Hafizabad',
  'Hajira',
  'Hala',
  'Hangu',
  'Haripur',
  'Haroonabad',
  'Hasilpur',
  'Hattian Bala',
  'Haveli Lakha',
  'Hub',
  'Hujra Shah Muqeem',
  'Hunza',
  'Hyderabad',
  'Isa Khel',
  'Islamabad',
  'Islamkot',
  'Jacobabad',
  'Jahanian',
  'Jalalpur Jattan',
  'Jalalpur Pirwala',
  'Jampur',
  'Jamshoro',
  'Jand',
  'Jaranwala',
  'Jatoi',
  'Jhang',
  'Jhelum',
  'Jiwani',
  'Kabirwala',
  'Kahror Pakka',
  'Kahuta',
  'Kalabagh',
  'Kalat',
  'Kallar Kahar',
  'Kallar Syedan',
  'Kamalia',
  'Kamar Mushani',
  'Kamoke',
  'Kandhkot',
  'Kandiaro',
  'Karachi',
  'Karak',
  'Kashmore',
  'Kasur',
  'Khairpur',
  'Khairpur Mirs',
  'Khairpur Nathan Shah',
  'Khanewal',
  'Khanpur',
  'Khaplu',
  'Kharan',
  'Kharian',
  'Khipro',
  'Khuiratta',
  'Khushab',
  'Khuzdar',
  'Kohat',
  'Kohlu',
  'Kot Addu',
  'Kot Diji',
  'Kot Momin',
  'Kotli',
  'Kotli Loharan',
  'Kotli Sattian',
  'Kotri',
  'Kuchlak',
  'Kulachi',
  'Kunri',
  'Lachi',
  'Lahore',
  'Lakhi',
  'Lakki Marwat',
  'Lalamusa',
  'Larkana',
  'Lasbela',
  'Layyah',
  'Liaquatpur',
  'Lodhran',
  'Loralai',
  'Mach',
  'Mailsi',
  'Malakand',
  'Mamu Kanjan',
  'Mananwala',
  'Mandi Bahauddin',
  'Mansehra',
  'Mardan',
  'Mastung',
  'Matiari',
  'Mehar',
  'Mehrabpur',
  'Mian Channu',
  'Mianwali',
  'Minchinabad',
  'Mingora (Swat)',
  'Mirpur (AJK)',
  'Mirpur Khas',
  'Mirpur Mathelo',
  'Mithi',
  'Moro',
  'Multan',
  'Muridke',
  'Murree',
  'Muslim Bagh',
  'Muzaffarabad',
  'Muzaffargarh',
  'Nagar',
  'Nankana Sahib',
  'Narowal',
  'Naukot',
  'Naushahro Feroze',
  'Nawabshah',
  'Nowshera',
  'Nowshera Virkan',
  'Nushki',
  'Oghi',
  'Okara',
  'Ormara',
  'Pakpattan',
  'Pallandri',
  'Panjgur',
  'Pano Akil',
  'Parachinar',
  'Pasni',
  'Pasrur',
  'Pattoki',
  'Peshawar',
  'Phalia',
  'Pind Dadan Khan',
  'Pindi Bhattian',
  'Pir Mahal',
  'Pishin',
  'Qadirpur',
  'Qila Abdullah',
  'Qila Saifullah',
  'Quetta',
  'Rabwah',
  'Rahim Yar Khan',
  'Rajanpur',
  'Ratodero',
  'Rawalakot',
  'Rawalpindi',
  'Renala Khurd',
  'Risalpur',
  'Rohri',
  'Sadiqabad',
  'Sahianwala',
  'Sahiwal',
  'Sakrand',
  'Salehpat',
  'Sambrial',
  'Sanghar',
  'Sangla Hill',
  'Sargodha',
  'Sehnsa',
  'Sehwan',
  'Serai Naurang',
  'Shabqadar',
  'Shahdadkot',
  'Shahdadpur',
  'Shakargarh',
  'Sharaqpur',
  'Sheikhupura',
  'Shikarpur',
  'Shorkot',
  'Shujabad',
  'Sialkot',
  'Sibi',
  'Sillanwali',
  'Sinjhoro',
  'Skardu',
  'Sohbatpur',
  'Sukheke Mandi',
  'Sukkur',
  'Surab',
  'Swabi',
  'Talagang',
  'Tandlianwala',
  'Tando Adam',
  'Tando Allahyar',
  'Tando Bago',
  'Tando Muhammad Khan',
  'Tangi',
  'Tangwani',
  'Tank',
  'Taunsa',
  'Taxila',
  'Thatta',
  'Thul',
  'Timergara',
  'Toba Tek Singh',
  'Tret',
  'Turbat',
  'Ubaro',
  'Ubauro',
  'Umerkot',
  'Usta Mohammad',
  'Vehari',
  'Wah Cantonment',
  'Wazirabad',
  'Yasin',
  'Yazman',
  'Zhob',
  'Ziarat',
  // Additional towns (de-duplicated; sorted at display time).
  'Havelian',
  'Dina',
  'Sarai Alamgir',
  'Jauharabad',
  'Quaidabad',
  'Kundian',
  'Khewra',
  'Sohawa',
  'Kunjah',
  'Chawinda',
  'Zafarwal',
  'Eminabad',
  'Ferozewala',
  'Shahkot',
  'Safdarabad',
  'Tulamba',
  'Abdul Hakim',
  'Hassan Abdal',
  'Hazro',
  'Fateh Jang',
  'Pindi Gheb',
  'Daultala',
  'Mandra',
  'Jhawarian',
  'Kot Radha Kishan',
  'Phool Nagar',
  'Sammundri',
  'Tibba Sultanpur',
  'Qadirpur Ran',
  'Ahmadpur Sial',
  '18-Hazari',
  'Takht Bhai',
  'Landi Kotal',
  'Jamrud',
  'Drosh',
  'Chakdara',
  'Dargai',
  'Topi',
  'Besham',
  'Khar',
  'Alpuri',
  'Wana',
  'Miran Shah',
  'Sadda',
  'Thall',
  'Pezu',
  'Uthal',
  'Bhit Shah',
  'Tando Jam',
  'Matli',
  'Golarchi',
  'Nagarparkar',
  'Diplo',
  'Chachro',
  'Qambar',
  'Warah',
  'Naudero',
  'Bakrani',
  'Kot Ghulam Muhammad',
  'Jhuddo',
  'Tando Jan Muhammad',
  'Sui',
  'Dhadar',
  'Duki',
  'Harnai',
  'Sanjawi',
  'Uch Sharif',
  'Naran',
  'Kaghan',
  'Kalam',
  'Bahrain',
  'Madyan',
  'Nathia Gali',
  'Shogran',
  'Saidu Sharif',
];

const List<String> itemConditions = ['New', 'Used'];

/// Optional pricing units (for food/grocery and bulk sellers). 'None' = blank.
const List<String> pricingUnits = [
  'None',
  'kg',
  'gram',
  'dozen',
  'piece',
  'plate',
  'litre',
  'pack',
  'box',
  'person',
  'hour',
  'day',
  'month',
];

/// Optional spec fields shown when posting/editing in certain categories
/// (e.g. car year & mileage, property bedrooms & area).
List<String> attributeFieldsFor(String category) {
  switch (category) {
    case 'Motors':
      return const ['Make / Brand', 'Year', 'KM driven'];
    case 'Properties':
      return const ['Bedrooms', 'Bathrooms', 'Area (sq ft / marla)'];
    case 'Mobiles & Tablets':
    case 'Electronics':
      return const ['Brand', 'Model'];
    case 'Commute & Rides':
      return const [
        'Route (From → To)',
        'Timing',
        'Seats available',
        'Monthly fare',
        'Per-trip fare',
      ];
    default:
      return const [];
  }
}

class MarketplaceCategory {
  final String title;
  final IconData icon;
  final List<String> subcategories;

  const MarketplaceCategory({
    required this.title,
    required this.icon,
    required this.subcategories,
  });
}

const List<MarketplaceCategory> appCategories = [
  MarketplaceCategory(title: 'All', icon: Icons.apps, subcategories: ['All']),
  MarketplaceCategory(
    title: 'Food & Grocery',
    icon: Icons.storefront,
    subcategories: [
      'Restaurants',
      'Supermarkets',
      'Grocery Stores',
      'Meat Shops',
      'Fruit & Vegetables',
      'Bakery & Sweets',
      'Dairy & Eggs',
      'Catering',
      'Home Kitchen',
    ],
  ),
  MarketplaceCategory(
    title: 'Motors',
    icon: Icons.directions_car,
    subcategories: [
      'Cars',
      'Motorcycles',
      'Auto Parts',
      'Boats',
      'Heavy Vehicles',
      'Number Plates',
      'Car Accessories',
      'Car Rental',
    ],
  ),
  MarketplaceCategory(
    title: 'Commute & Rides',
    icon: Icons.commute,
    subcategories: [
      'Carpool',
      'Daily Pick & Drop',
      'School / College Van',
      'Office Transport',
      'Bike Ride',
      'Rent a Car with Driver',
      'Driver Services',
      'Intercity Shared Ride',
    ],
  ),
  MarketplaceCategory(
    title: 'Properties',
    icon: Icons.home,
    subcategories: [
      'Apartments for Rent',
      'Apartments for Sale',
      'Villas for Rent',
      'Villas for Sale',
      'Rooms for Rent',
      'Commercial Property',
      'Holiday Homes',
      'Land',
      'Property Services',
    ],
  ),
  MarketplaceCategory(
    title: 'Mobiles & Tablets',
    icon: Icons.phone_android,
    subcategories: [
      'Mobile Phones',
      'Tablets',
      'Smart Watches',
      'Mobile Accessories',
      'SIM Cards',
      'Repair Services',
    ],
  ),
  MarketplaceCategory(
    title: 'Electronics',
    icon: Icons.devices,
    subcategories: [
      'Computers & Laptops',
      'TV & Audio',
      'Cameras',
      'Gaming',
      'Home Appliances',
      'Kitchen Appliances',
      'Computer Accessories',
      'Security Cameras',
    ],
  ),
  MarketplaceCategory(
    title: 'Home & Furniture',
    icon: Icons.chair,
    subcategories: [
      'Furniture',
      'Home Decor',
      'Garden & Outdoor',
      'Kitchenware',
      'Lighting',
      'Beds & Mattresses',
      'Tools',
      'Moving & Storage',
    ],
  ),
  MarketplaceCategory(
    title: 'Men Essentials',
    icon: Icons.man,
    subcategories: [
      'Men Clothing',
      'Men Shoes',
      'Watches',
      'Wallets & Bags',
      'Grooming',
      'Perfumes',
      'Sportswear',
      'Sunglasses',
    ],
  ),
  MarketplaceCategory(
    title: 'Women Essentials',
    icon: Icons.woman,
    subcategories: [
      'Women Clothing',
      'Women Shoes',
      'Bags',
      'Jewellery',
      'Beauty & Makeup',
      'Perfumes',
      'Watches',
      'Accessories',
    ],
  ),
  MarketplaceCategory(
    title: 'Kids Essentials',
    icon: Icons.child_care,
    subcategories: [
      'Kids Clothing',
      'Kids Shoes',
      'Toys',
      'Baby Gear',
      'Strollers',
      'School Items',
      'Kids Furniture',
      'Maternity',
    ],
  ),
  MarketplaceCategory(
    title: 'Jobs',
    icon: Icons.work,
    subcategories: [
      'Accounting',
      'Admin',
      'Customer Service',
      'Drivers',
      'Engineering',
      'Hospitality',
      'IT',
      'Marketing',
      'Sales',
      'Real Estate',
      'Construction',
      'Domestic Staff',
    ],
  ),
  MarketplaceCategory(
    title: 'Services',
    icon: Icons.handyman,
    subcategories: [
      'Cleaning',
      'Maintenance',
      'Moving',
      'Car Services',
      'Beauty Services',
      'Tutoring',
      'Photography',
      'Events',
      'Legal Services',
      'Business Services',
      'Home Repair',
      'AC Repair',
      'Plumbing',
      'Electrical',
    ],
  ),
  MarketplaceCategory(
    title: 'Pets',
    icon: Icons.pets,
    subcategories: [
      'Cats',
      'Dogs',
      'Birds',
      'Fish',
      'Pet Food',
      'Pet Accessories',
      'Pet Services',
      'Adoption',
    ],
  ),
  MarketplaceCategory(
    title: 'Sports & Hobbies',
    icon: Icons.sports_soccer,
    subcategories: [
      'Gym Equipment',
      'Bicycles',
      'Sports Gear',
      'Musical Instruments',
      'Books',
      'Collectibles',
      'Camping',
      'Tickets',
    ],
  ),
  MarketplaceCategory(
    title: 'Business & Industrial',
    icon: Icons.business_center,
    subcategories: [
      'Office Furniture',
      'Restaurant Equipment',
      'Industrial Equipment',
      'Medical Equipment',
      'Retail Equipment',
      'Wholesale',
      'Machinery',
    ],
  ),
  MarketplaceCategory(
    title: 'Community',
    icon: Icons.groups,
    subcategories: [
      'Classes',
      'Activities',
      'Lost & Found',
      'Volunteers',
      'Announcements',
      'Free Stuff',
    ],
  ),
];

/// Whole categories that are advertise-only — no online Buy Now / checkout.
/// Buyers contact the seller (call/WhatsApp/chat) and deal in person instead.
const Set<String> advertiseOnlyCategories = {
  'Properties',
  'Jobs',
  'Services',
  'Community',
  'Commute & Rides',
};

/// Big-ticket / non-shippable subcategories (e.g. within Motors) that are
/// advertise-only even though the rest of their category can be bought online.
/// Small, shippable items like Auto Parts / Car Accessories stay buyable.
const Set<String> advertiseOnlySubcategories = {
  'Cars',
  'Motorcycles',
  'Boats',
  'Heavy Vehicles',
  'Car Rental',
};

/// Whether a listing supports the online Buy Now / order checkout.
MarketplaceCategory categoryByTitle(String title) {
  return appCategories.firstWhere(
    (category) => category.title == title,
    orElse: () => appCategories.first,
  );
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Web Push (VAPID) public key from Firebase Console → Cloud Messaging →
/// "Web configuration" → Web Push certificates. Leave empty to disable web
/// push until configured (the app still works fully without it).
