// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// The domain Firebase's OAuth handler is served from.
  ///
  /// This was briefly pointed at whatever host the app was served from, to
  /// make the sign-in popup same-origin and dodge a Cross-Origin-Opener-Policy
  /// problem. It made Google sign-in fail earlier and harder:
  ///
  ///   Error 400: redirect_uri_mismatch
  ///   redirect_uri = https://pakbazar24.com/__/auth/handler
  ///
  /// Adding a domain to Firebase Auth's authorised list does NOT add it to the
  /// OAuth client's authorised redirect URIs, and only the firebaseapp.com
  /// handler is registered there. So the popup opened straight onto a Google
  /// error page — worse than the COOP stall it was meant to fix, because that
  /// one at least happened after signing in.
  ///
  /// The COOP problem is dodged by using signInWithRedirect instead of a popup
  /// (see social_auth.dart), which needs no opener relationship at all.
  ///
  /// TO GO BACK TO THE SAME-ORIGIN POPUP: add
  ///   https://pakbazar24.com/__/auth/handler
  ///   https://www.pakbazar24.com/__/auth/handler
  /// to the "Web client (auto created by Google Service)" credential under
  /// APIs & Services -> Credentials in the Google Cloud console. There is no
  /// API for it; it has to be done in the console.
  static const String webAuthDomain = 'markethub-80276.firebaseapp.com';

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: 'AIzaSyCERNmuaRMssjATHPc3MoJPtfLeVtqykKA',
    appId: '1:541505846653:web:2afe478f1fb52e358a2014',
    messagingSenderId: '541505846653',
    projectId: 'markethub-80276',
    authDomain: webAuthDomain,
    storageBucket: 'markethub-80276.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2JdMn-metZZ-Qh8GsSdw8APQH-zlLTFY',
    appId: '1:541505846653:android:43c0c2c9c92db4148a2014',
    messagingSenderId: '541505846653',
    projectId: 'markethub-80276',
    storageBucket: 'markethub-80276.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4MtDXh5ybHO8lwpPlRaXBcwuGXhM_xUI',
    appId: '1:541505846653:ios:deb9017ac06595108a2014',
    messagingSenderId: '541505846653',
    projectId: 'markethub-80276',
    storageBucket: 'markethub-80276.firebasestorage.app',
    iosClientId:
        '541505846653-lbaa69m2udcuril9tlp8n2si30488ehi.apps.googleusercontent.com',
    iosBundleId: 'com.example.markethub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4MtDXh5ybHO8lwpPlRaXBcwuGXhM_xUI',
    appId: '1:541505846653:ios:deb9017ac06595108a2014',
    messagingSenderId: '541505846653',
    projectId: 'markethub-80276',
    storageBucket: 'markethub-80276.firebasestorage.app',
    iosClientId:
        '541505846653-lbaa69m2udcuril9tlp8n2si30488ehi.apps.googleusercontent.com',
    iosBundleId: 'com.example.markethub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCERNmuaRMssjATHPc3MoJPtfLeVtqykKA',
    appId: '1:541505846653:web:9c882ed5a90d3ff38a2014',
    messagingSenderId: '541505846653',
    projectId: 'markethub-80276',
    authDomain: 'markethub-80276.firebaseapp.com',
    storageBucket: 'markethub-80276.firebasestorage.app',
  );
}
