// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// The domain Firebase's OAuth handler is served from.
  ///
  /// This was briefly pointed at whatever host was serving the app, chasing a
  /// Cross-Origin-Opener-Policy warning in the console. That warning turns out
  /// to come from accounts.google.com's own REPORT-ONLY policy and enforces
  /// nothing — but the change broke Google sign-in on the website outright:
  ///
  ///   Error 400: redirect_uri_mismatch
  ///   redirect_uri = https://pakbazar24.com/__/auth/handler
  ///
  /// Adding a domain to Firebase Auth's authorised list does NOT add it to the
  /// OAuth client's authorised redirect URIs. Only the firebaseapp.com handler
  /// is registered there, so that is the only value that works.
  ///
  /// TO MOVE THE FLOW ONTO OUR OWN DOMAIN, on the "Web client (auto created by
  /// Google Service)" credential under APIs & Services -> Credentials:
  ///   Authorised redirect URIs   += https://pakbazar24.com/__/auth/handler
  ///                                 https://www.pakbazar24.com/__/auth/handler
  ///   Authorised JavaScript origins += https://pakbazar24.com
  ///                                    https://www.pakbazar24.com
  /// Both lists are missing our host today, verified separately. There is no
  /// API for either; it is a console job.
  static const String webAuthDomain = 'markethub-80276.firebaseapp.com';

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: 'AIzaSyCERNmuaRMssjATHPc3MoJPtfLeVtqykKA',
    appId: '1:541505846653:web:2afe478f1fb52e358a2014',
    messagingSenderId: '541505846653',
    projectId: 'markethub-80276',
    authDomain: webAuthDomain,
    storageBucket: 'markethub-80276.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2JdMn-metZZ-Qh8GsSdw8APQH-zlLTFY',
    appId: '1:541505846653:android:43c0c2c9c92db4148a2014',
    messagingSenderId: '541505846653',
    projectId: 'markethub-80276',
    storageBucket: 'markethub-80276.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4MtDXh5ybHO8lwpPlRaXBcwuGXhM_xUI',
    appId: '1:541505846653:ios:deb9017ac06595108a2014',
    messagingSenderId: '541505846653',
    projectId: 'markethub-80276',
    storageBucket: 'markethub-80276.firebasestorage.app',
    iosClientId:
        '541505846653-lbaa69m2udcuril9tlp8n2si30488ehi.apps.googleusercontent.com',
    iosBundleId: 'com.example.markethub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4MtDXh5ybHO8lwpPlRaXBcwuGXhM_xUI',
    appId: '1:541505846653:ios:deb9017ac06595108a2014',
    messagingSenderId: '541505846653',
    projectId: 'markethub-80276',
    storageBucket: 'markethub-80276.firebasestorage.app',
    iosClientId:
        '541505846653-lbaa69m2udcuril9tlp8n2si30488ehi.apps.googleusercontent.com',
    iosBundleId: 'com.example.markethub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCERNmuaRMssjATHPc3MoJPtfLeVtqykKA',
    appId: '1:541505846653:web:9c882ed5a90d3ff38a2014',
    messagingSenderId: '541505846653',
    projectId: 'markethub-80276',
    authDomain: 'markethub-80276.firebaseapp.com',
    storageBucket: 'markethub-80276.firebasestorage.app',
  );
}
